version: "3.3"
services:

  testapp1:
    build:
      context: ./test-app
    ports:
      - "8081:8081"
    networks:
      - backend

  testapp2:
    build:
      context: ./test-app-1
    ports:
      - "8082:8082"
    networks:
      - backend

  balance:
    image: nginx
    volumes:
      - nginx-config:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  nginx-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./nginx
